/**
 * Backend Server — LeanSecurityProject
 *
 * This server acts as the integration layer between the frontend UI and the
 * Lean 4 formal verification engine.
 *
 * Key upgrade from prototype: the /verify endpoint now dynamically generates
 * a Lean proof file from the user's model input, executes it via the Lean CLI,
 * and returns a result based on real formal verification output — not hardcoded
 * responses.
 */

const express = require("express");
const path = require("path");
const { exec } = require("child_process");
const fs = require("fs");
const os = require("os");

const app = express();
const PORT = 3000;

// Path to lean executable — installed via elan on Windows
const LEAN_PATH = "C:\\Users\\veerp\\.elan\\bin\\lean.exe";

app.use(express.json());
app.use(express.static(path.join(__dirname, "../frontend")));
app.use("/proofs", express.static(__dirname));

// ---------------------------------------------------------------------------
// Model Parser
// ---------------------------------------------------------------------------

/**
 * Parses the user's textarea input into lists of authorised and unauthorised
 * users. Each line is expected in the format:  "Name: authorised" or
 * "Name: unauthorised"  (case-insensitive, extra whitespace tolerated).
 *
 * Returns: { authorised: string[], unauthorised: string[], allUsers: string[] }
 *
 * Example input:
 *   Alice: authorised
 *   Bob: authorised
 *   Eve: unauthorised
 */
function parseModel(modelText) {
  const authorised = [];
  const unauthorised = [];

  const lines = modelText.split("\n");

  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed) return;

    const parts = trimmed.split(":");
    if (parts.length < 2) return;

    const name = parts[0].trim();
    const status = parts[1].trim().toLowerCase();

    // Sanitise: only allow valid Lean identifier characters in user names.
    // This prevents injection into the generated Lean source.
    if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(name)) return;

    if (status === "authorised") {
      authorised.push(name);
    } else if (status === "unauthorised") {
      unauthorised.push(name);
    }
  });

  return {
    authorised,
    unauthorised,
    allUsers: [...authorised, ...unauthorised]
  };
}

// ---------------------------------------------------------------------------
// Lean Code Generators
// ---------------------------------------------------------------------------
// Each function produces a complete, self-contained Lean 4 source file as a
// string, parameterised by the parsed user model.
//
// All three proofs use the same contrapositive pattern:
//   forall u, not authorised u -> not canDo u
// Proven by intro + unfold + exact, which Lean 4 accepts cleanly for any
// user inductive type regardless of how many constructors are present.

/**
 * Generates a Lean 4 access control proof for the given user lists.
 *
 * Policy:  authorised users may access resources; others are denied.
 * Theorem: any user who is not authorised cannot access.
 */
function generateAccessControlLean(authorised, unauthorised, allUsers) {
  const userConstructors = allUsers.join(" | ");

  const matchArms = allUsers.map(u => {
    return `  | ${u} => ${authorised.includes(u) ? "True" : "False"}`;
  }).join("\n");

  return `-- Auto-generated by LeanSecurityProject backend
-- Property: Access Control
-- Users: ${allUsers.join(", ")}

inductive User | ${userConstructors}
open User

def authorised : User -> Prop
${matchArms}

def canAccess (u : User) : Prop := authorised u

theorem access_control_is_secure :
  forall u : User, Not (authorised u) -> Not (canAccess u) := by
  intro u h
  unfold canAccess
  exact h
`;
}

/**
 * Generates a Lean 4 authentication proof for the given user lists.
 *
 * Policy:  only authenticated users may access the system.
 * Theorem: unauthenticated users cannot access.
 */
function generateAuthenticationLean(authorised, unauthorised, allUsers) {
  const userConstructors = allUsers.join(" | ");

  const matchArms = allUsers.map(u => {
    return `  | ${u} => ${authorised.includes(u) ? "True" : "False"}`;
  }).join("\n");

  return `-- Auto-generated by LeanSecurityProject backend
-- Property: Authentication
-- Users: ${allUsers.join(", ")}

inductive User | ${userConstructors}
open User

def authenticated : User -> Prop
${matchArms}

def canAccess (u : User) : Prop := authenticated u

theorem authentication_secure :
  forall u : User, Not (authenticated u) -> Not (canAccess u) := by
  intro u h
  unfold canAccess
  exact h
`;
}

/**
 * Generates a Lean 4 integrity proof for the given user lists.
 *
 * Policy:  only authorised users may modify data.
 * Theorem: unauthorised users cannot modify.
 */
function generateIntegrityLean(authorised, unauthorised, allUsers) {
  const userConstructors = allUsers.join(" | ");

  const matchArms = allUsers.map(u => {
    return `  | ${u} => ${authorised.includes(u) ? "True" : "False"}`;
  }).join("\n");

  return `-- Auto-generated by LeanSecurityProject backend
-- Property: Integrity
-- Users: ${allUsers.join(", ")}

inductive User | ${userConstructors}
open User

def authorised : User -> Prop
${matchArms}

def canModify (u : User) : Prop := authorised u

theorem integrity_secure :
  forall u : User, Not (authorised u) -> Not (canModify u) := by
  intro u h
  unfold canModify
  exact h
`;
}

// ---------------------------------------------------------------------------
// Lean Executor
// ---------------------------------------------------------------------------

/**
 * Writes a Lean source string to a temporary file, executes lean.exe on it,
 * and resolves with { success: boolean, output: string }.
 *
 * Uses os.tmpdir() so we never write into the project source tree.
 * The temp file is deleted after execution regardless of outcome.
 */
function runLean(leanSource) {
  return new Promise((resolve) => {
    const tmpFile = path.join(os.tmpdir(), `lean_verify_${Date.now()}.lean`);

    fs.writeFileSync(tmpFile, leanSource, "utf8");

    // 15-second timeout — Lean type-checking is fast for small files
    exec(`"${LEAN_PATH}" "${tmpFile}"`, { timeout: 15000 }, (error, stdout, stderr) => {
      // Always clean up the temp file
      try { fs.unlinkSync(tmpFile); } catch (_) {}

      if (error) {
        resolve({ success: false, output: stderr || stdout || error.message });
      } else {
        resolve({ success: true, output: stdout || "Proof verified." });
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Verification Endpoint
// ---------------------------------------------------------------------------

/**
 * POST /verify
 *
 * Accepts: { property: string, model: string }
 * Returns: { result: string, explanation: string, proofFile: string | null,
 *            generatedLean: string }
 *
 * The generatedLean field is returned so the frontend can display the exact
 * Lean source that was submitted to the verifier — useful for transparency
 * and the demo video.
 */
app.post("/verify", async (req, res) => {
  const { property, model } = req.body;

  // --- 1. Parse the user model ---
  const parsed = parseModel(model || "");

  if (parsed.allUsers.length === 0) {
    return res.json({
      result: "Error",
      explanation: "No valid users found in the model. Use the format:\n  Alice: authorised\n  Eve: unauthorised",
      proofFile: null,
      generatedLean: null
    });
  }

  if (parsed.authorised.length === 0) {
    return res.json({
      result: "Error",
      explanation: "At least one authorised user is required to generate a valid proof.",
      proofFile: null,
      generatedLean: null
    });
  }

  // --- 2. Generate the appropriate Lean source ---
  let leanSource;
  let proofFile;

  try {
    switch (property) {
      case "access_control":
        leanSource = generateAccessControlLean(
          parsed.authorised, parsed.unauthorised, parsed.allUsers
        );
        proofFile = "AccessControl.lean";
        break;

      case "authentication":
        leanSource = generateAuthenticationLean(
          parsed.authorised, parsed.unauthorised, parsed.allUsers
        );
        proofFile = "Authentication.lean";
        break;

      case "integrity":
        leanSource = generateIntegrityLean(
          parsed.authorised, parsed.unauthorised, parsed.allUsers
        );
        proofFile = "Integrity.lean";
        break;

      default:
        return res.json({
          result: "Error",
          explanation: "Unknown property selected.",
          proofFile: null,
          generatedLean: null
        });
    }
  } catch (genError) {
    return res.json({
      result: "Error",
      explanation: `Failed to generate Lean proof: ${genError.message}`,
      proofFile: null,
      generatedLean: null
    });
  }

  // --- 3. Run Lean and return result ---
  const { success, output } = await runLean(leanSource);

  const userSummary =
    `Authorised users: ${parsed.authorised.join(", ") || "none"}\n` +
    `Unauthorised users: ${parsed.unauthorised.join(", ") || "none"}`;

  if (success) {
    return res.json({
      result: "Verified",
      explanation:
        `Formal verification passed using Lean 4.\n\n${userSummary}\n\n` +
        `Property: ${property.replace(/_/g, " ")} -- all proof obligations discharged.`,
      proofFile,
      generatedLean: leanSource
    });
  } else {
    return res.json({
      result: "Verification Failed",
      explanation:
        `Lean 4 could not verify this property with the given model.\n\n${userSummary}\n\n` +
        `Lean output:\n${output}`,
      proofFile,
      generatedLean: leanSource
    });
  }
});

// ---------------------------------------------------------------------------
// Start server
// ---------------------------------------------------------------------------

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`Backend running at http://localhost:${PORT}`);
    console.log(`Using Lean at: ${LEAN_PATH}`);
  });
}

module.exports = app;
 
