/**
 * Backend Server — LeanSecurityProject
 *
 * This server acts as the integration layer between the frontend UI and the
 * LEAN 4 formal verification engine.
 *
 * Connect the frontend UI to the LEAN 4 verifier. 
 * It takes user input, generates a LEAN proof, runs it,
 * and returns whether the property was verified.
 */

const express = require("express");
const path = require("path");
const { exec } = require("child_process");
const fs = require("fs");
const os = require("os");

const app = express();
const PORT = 3000;

// Path to lean executable — installed via elan on Windows
const LEAN_PATH = "C:\\Users\\veerp\\.elan\\bin\\lean.exe";

app.use(express.json());
app.use(express.static(path.join(__dirname, "../frontend")));
app.use("/proofs", express.static(__dirname));

// ---------------------------------------------------------------------------
// Model Parser
// ---------------------------------------------------------------------------

/**
 * Converts the user input text into authorised and unauthorised user lists.
 * Also filters out invalid names to prevent issues in the generated LEAN code.

 * users. Each line is expected in the format:  "Name: authorised" or
 * "Name: unauthorised"  (case-insensitive, extra whitespace tolerated).
 *
 * Returns: { authorised: string[], unauthorised: string[], allUsers: string[] }
 *
 * Example input:
 *   Alice: authorised
 *   Bob: authorised
 *   Eve: unauthorised
 */
function parseModel(modelText) {
  const authorised = [];
  const unauthorised = [];

  const lines = modelText.split("\n");

  lines.forEach(line => {
    const trimmed = line.trim();
    if (!trimmed) return;

    const parts = trimmed.split(":");
    if (parts.length < 2) return;

    const name = parts[0].trim();
    const status = parts[1].trim().toLowerCase();

    // Only allow valid identifier names to avoid breaking the LEAN code
    // or allowing unintended input into the generated proof
    if (!/^[A-Za-z][A-Za-z0-9_]*$/.test(name)) return;

    if (status === "authorised") {
      authorised.push(name);
    } else if (status === "unauthorised") {
      unauthorised.push(name);
    }
  });

  return {
    authorised,
    unauthorised,
    allUsers: [...authorised, ...unauthorised]
  };
}

// ---------------------------------------------------------------------------
// LEAN Code Generators
// ---------------------------------------------------------------------------
// Each function produces a complete, self-contained LEAN 4 source file as a
// string, parameterised by the parsed user model.
//
// All three proofs use the same contrapositive pattern:
//   forall u, not authorised u -> not canDo u
// Proven by intro + unfold + exact, which LEAN 4 accepts cleanly for any
// user inductive type regardless of how many constructors are present.

// Builds a LEAN proof for access control based on the user model
// Unauthorised users should not be able to access the system.
function generateAccessControlLean(authorised, unauthorised, allUsers) {
  const userConstructors = allUsers.join(" | ");

  const matchArms = allUsers.map(u => {
    return `  | ${u} => ${authorised.includes(u) ? "True" : "False"}`;
  }).join("\n");

  return `-- Auto-generated by LeanSecurityProject backend
-- Property: Access Control
-- Users: ${allUsers.join(", ")}

inductive User | ${userConstructors}
open User

def authorised : User -> Prop
${matchArms}

def canAccess (u : User) : Prop := authorised u

theorem access_control_is_secure :
  forall u : User, Not (authorised u) -> Not (canAccess u) := by
  intro u h
  unfold canAccess
  exact h
`;
}

// Builds a LEAN proof for access authentication based on the user model
// Unauthenticated users should not be able to access the system.
function generateAuthenticationLean(authorised, unauthorised, allUsers) {
  const userConstructors = allUsers.join(" | ");

  const matchArms = allUsers.map(u => {
    return `  | ${u} => ${authorised.includes(u) ? "True" : "False"}`;
  }).join("\n");

  return `-- Auto-generated by LeanSecurityProject backend
-- Property: Authentication
-- Users: ${allUsers.join(", ")}

inductive User | ${userConstructors}
open User

def authenticated : User -> Prop
${matchArms}

def canAccess (u : User) : Prop := authenticated u

theorem authentication_secure :
  forall u : User, Not (authenticated u) -> Not (canAccess u) := by
  intro u h
  unfold canAccess
  exact h
`;
}

// Builds a LEAN proof for integrity based on the user model
// Unauthorised users should not be able to modify data in the system.
function generateIntegrityLean(authorised, unauthorised, allUsers) {
  const userConstructors = allUsers.join(" | ");

  const matchArms = allUsers.map(u => {
    return `  | ${u} => ${authorised.includes(u) ? "True" : "False"}`;
  }).join("\n");

  return `-- Auto-generated by LeanSecurityProject backend
-- Property: Integrity
-- Users: ${allUsers.join(", ")}

inductive User | ${userConstructors}
open User

def authorised : User -> Prop
${matchArms}

def canModify (u : User) : Prop := authorised u

theorem integrity_secure :
  forall u : User, Not (authorised u) -> Not (canModify u) := by
  intro u h
  unfold canModify
  exact h
`;
}

// ---------------------------------------------------------------------------
// LEAN Executor
// ---------------------------------------------------------------------------

// Runs the generated LEAN code by writing it to a temporary file
// and executing the LEAN CLI. The file is deleted afterwards.
function runLean(leanSource) {
  return new Promise((resolve) => {
    const tmpFile = path.join(os.tmpdir(), `lean_verify_${Date.now()}.lean`);

    fs.writeFileSync(tmpFile, leanSource, "utf8");

    // 15-second timeout — Lean type-checking is fast for small files
    exec(`"${LEAN_PATH}" "${tmpFile}"`, { timeout: 15000 }, (error, stdout, stderr) => {
      // Always clean up the temp file
      try { fs.unlinkSync(tmpFile); } catch (_) {}

      if (error) {
        resolve({ success: false, output: stderr || stdout || error.message });
      } else {
        resolve({ success: true, output: stdout || "Proof verified." });
      }
    });
  });
}

// ---------------------------------------------------------------------------
// Verification Endpoint
// ---------------------------------------------------------------------------

//POST /verify
 //This is the main verification endpoint.
 //Receives the user model and selected property,
 //generates a LEAN proof, runs it and returns the result.
 
 //The generatedLean field is returned so the frontend can display the exact
 //LEAN source that was submitted to the verifier — useful for transparency.
 
app.post("/verify", async (req, res) => {
  const { property, model } = req.body;

  // --- 1. Parse the user model ---
  const parsed = parseModel(model || "");

  if (parsed.allUsers.length === 0) {
    return res.json({
      result: "Error",
      explanation: "No valid users found in the model. Use the format:\n  Alice: authorised\n  Eve: unauthorised",
      proofFile: null,
      generatedLean: null
    });
  }

  if (parsed.authorised.length === 0) {
    return res.json({
      result: "Error",
      explanation: "At least one authorised user is required to generate a valid proof.",
      proofFile: null,
      generatedLean: null
    });
  }

  // --- 2. Generate the appropriate LEAN source ---
  let leanSource;
  let proofFile;

  try {
    switch (property) {
      case "access_control":
        leanSource = generateAccessControlLean(
          parsed.authorised, parsed.unauthorised, parsed.allUsers
        );
        proofFile = "AccessControl.lean";
        break;

      case "authentication":
        leanSource = generateAuthenticationLean(
          parsed.authorised, parsed.unauthorised, parsed.allUsers
        );
        proofFile = "Authentication.lean";
        break;

      case "integrity":
        leanSource = generateIntegrityLean(
          parsed.authorised, parsed.unauthorised, parsed.allUsers
        );
        proofFile = "Integrity.lean";
        break;

      default:
        return res.json({
          result: "Error",
          explanation: "Unknown property selected.",
          proofFile: null,
          generatedLean: null
        });
    }
  } catch (genError) {
    return res.json({
      result: "Error",
      explanation: `Failed to generate Lean proof: ${genError.message}`,
      proofFile: null,
      generatedLean: null
    });
  }

  // --- 3. Run LEAN and return result ---
  const { success, output } = await runLean(leanSource);

  const userSummary =
    `Authorised users: ${parsed.authorised.join(", ") || "none"}\n` +
    `Unauthorised users: ${parsed.unauthorised.join(", ") || "none"}`;

  if (success) {
    return res.json({
      result: "Verified",
      explanation:
        `Formal verification passed using Lean 4.\n\n${userSummary}\n\n` +
        `Property: ${property.replace(/_/g, " ")} -- all proof obligations discharged.`,
      proofFile,
      generatedLean: leanSource
    });
  } else {
    return res.json({
      result: "Verification Failed",
      explanation:
        `Lean 4 could not verify this property with the given model.\n\n${userSummary}\n\n` +
        `Lean output:\n${output}`,
      proofFile,
      generatedLean: leanSource
    });
  }
});

// ---------------------------------------------------------------------------
// Start server
// ---------------------------------------------------------------------------

if (require.main === module) {
  app.listen(PORT, () => {
    console.log(`Backend running at http://localhost:${PORT}`);
    console.log(`Using Lean at: ${LEAN_PATH}`);
  });
}

module.exports = app;
 
